### ISSUE TITLE
"dd-nodrag" do not work

### ISSUE THREAD

**Issue by lifesimple** [dbushell/Nestable#169]
i add the class `dd-nodrag` in the index.html(demo) like follow
```
 <div class="dd dd-nodrag" id="nestable">
            <ol class="dd-list">
                <li class="dd-item" data-id="1">
                    <div class="dd-handle dd-nodrag">Item 1</div>
                </li>
                <li class="dd-item dd-nodrag" data-id="2">
                    <div class="dd-handle dd-nodrag">Item 2</div>
                    <ol class="dd-list">
                        <li class="dd-item" data-id="3"><div class="dd-handle dd-nodrag">Item 3</div></li>
...
```

i'm not sure where to add the default class `dd-nodrag`, so i have tried to add `dd-nodrag`  in "dd/dd-item/dd-handle"(element).
but each of above does not work in chrome45/ff/ie11, i can also drag the items.

what's wrong and how to make it correct?
thanks.

**Comment by avatar29A** [comment]
You have to remove dd-handle class.

**Comment by lifesimple** [comment]
@avatar29A  it works,thanks so much.
